about/urls.py
from django.urls import path

from about import views

app_name = 'about'
urlpatterns = [
    path('', views.AboutUs.as_view(), name='about-us'),
]

constructon_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('projects/', include('projects.urls')),
    path('about/', include('about.urls')),
    path('service/', include('service.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from home import views
app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

projects/urls.py
from django.urls import path

from projects import views

app_name = 'projects'

urlpatterns = [
    path('<int:pk>/', views.ProjectDetail.as_view(), name='project-detail'),
]

service/urls.py
from django.urls import path

from service import views

app_name = 'service'

urlpatterns = [
    path('', views.ServiceView.as_view(), name='service'),
]

about/models.py
from django.db import models


# Create your models here.
class AboutContent(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title


class AboutPromo(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    icon_name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title


class WorkPlan(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

blog/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models


# Create your models here.
class Settings(models.Model):
    title = models.CharField(max_length=100)
    header_logo = models.ImageField(upload_to='Logo', blank=True)
    footer_logo =models.ImageField(upload_to='Logo', blank=True)
    favicon =models.ImageField(upload_to='Logo', blank=True)
    description = models.TextField(blank=True)
    company = models.CharField(max_length=50)
    address = models.TextField(blank=True)
    phone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    facebook = models.URLField(max_length=200, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

projects/models.py
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils.safestring import mark_safe


class ProjectCategory(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class ProjectManager(models.Manager):
    def all_categories(self):
        qs = self.get_queryset()
        return qs.select_related('category')

class Project(models.Model):
    category = models.ForeignKey(ProjectCategory, on_delete=models.CASCADE, related_name='p_category')
    title = models.CharField(max_length=255)
    sub_title = models.TextField(blank=True)
    description = models.TextField(blank=True)
    feature_image = models.ImageField(upload_to='project_image', blank=True)
    architects = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    area = models.FloatField(default=0.00)
    project_start = models.DateField(blank=True)
    project_end = models.DateField(blank=True)
    manufactures = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProjectManager()

    def __str__(self):
        return self.title

    def image_url(self):
        if self.feature_image:
            return self.feature_image.url
        else:
            return ''

    def image_tag(self):
        return mark_safe('<img src="{}" height="70" width="60"/>'.format(self.image_url))

    def get_absolute_url(self):
        return reverse('projects:project-detail', kwargs={'pk': self.pk})


class ProjectImageManager(models.Manager):
    def all_images(self):
        qs = self.get_queryset()
        return qs.select_related('project')
class ProjectImage(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='project_image')
    image = models.ImageField(upload_to='project_image', blank=True)
    objects = ProjectImageManager()
    def __str__(self):
        return self.project.title

service/models.py
from django.db import models

# Create your models here.
class Service(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    icon_name = models.CharField(max_length=50)

    def __str__(self):
        return self.title

team/models.py
from django.db import models

# Create your models here.

testimonial/models.py
from django.db import models

# Create your models here.

about/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from about.models import AboutContent, AboutPromo, WorkPlan


class AboutUs(TemplateView):
    template_name = 'about/about_us.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['about_content'] = AboutContent.objects.first()
        context['about_promo'] = AboutPromo.objects.all()
        context['work_plan'] = WorkPlan.objects.all()
        return context

blog/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from about.models import AboutContent, AboutPromo
from projects.models import Project


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['projects'] = Project.objects.all()
        context['about_content'] = AboutContent.objects.first()
        context['about_promo'] = AboutPromo.objects.all()
        return context

projects/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView

from projects.models import Project


class ProjectDetail(DetailView):
    template_name = 'project/project_detail.html'
    context_object_name = 'single_project'
    queryset = Project.objects.all_categories()

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['images'] = Project.project_image.all()
    #     return context

service/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

from service.models import Service


class ServiceView(TemplateView):
    template_name = 'service/service.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['services'] = Service.objects.all()
        return context

team/views.py
from django.shortcuts import render

# Create your views here.

testimonial/views.py
from django.shortcuts import render

# Create your views here.

templates/about/about_us.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Indico | About US{% endblock title %}
{% block main_content %}
<section class="page-header padding">
    <div class="container">
        <div class="page-content text-center">
            <h2>About us</h2>
            <p>Construction & Building Html Template.</p>
        </div>
    </div>
</section>
<section class="about-section padding">
    <div class="container">
        <div class="row about-wrap">
            <div class="col-lg-6 sm-padding">
                <div class="about-content wow fadeInLeft">
                    <h2>{{ about_content.title }}</h2>
                    <p>{{ about_content.description }}</p>
                    <a href="{% url 'about:about-us' %}" class="default-btn">More About Us</a>
                </div>
            </div>
            <div class="col-lg-6 sm-padding">
                <ul class="about-promo">
                    {% for item in about_promo %}
                    <li class="about-promo-item wow fadeInUp">
                        <i class="flaticon-{{ item.icon_name }}"></i>
                        <div>
                            <h3>{{ item.title }}</h3>
                            <p>{{ item.description }}</p>
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="work-pro-section padding">
    <div class="container">
        <div class="row">
            {% for plan in work_plan %}
            <div class="col-lg-3 col-sm-6 sm-padding">
                <div class="work-pro-item text-center">
                    <span class="number">{{ forloop.counter }}</span>
                    <div class="number-line"></div>
                    <h3>{{ plan.title }}</h3>
                    <p>{{ plan.description }}</p>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</section>
<section class="content-section padding">
    <div class="container">
        <div class="row content-wrap">
            <div class="col-lg-6 sm-padding wow fadeInLeft" data-wow-delay="100ms">
                <img class="box-shadow" src="{% static 'img/content-1.jpg' %}" alt="img">
            </div>
            <div class="col-lg-6 sm-padding">
                <div class="content-info wow fadeInRight" data-wow-delay="300ms">
                    <span>Explore The Features</span>
                    <h2>Offering the most complete integrated package!</h2>
                    <p>We are committed to building a sustainable future by fostering a collaborative spirit that
                        creates exceptional experiences, balanced relationships, and community built environment.
                        Building isn’t just job. It's our passion. With every project we undertake, we set the bar high
                        and provide the best industry.</p>
                    <a href="#" class="default-btn">Get Free Quote</a>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="testimonial-section bg-grey padding">
    <div class="dots"></div>
    <div class="container">
        <div class="section-heading text-center mb-40 wow fadeInUp" data-wow-delay="100ms">
            <span>Testimonial</span>
            <h2>What people says</h2>
        </div>
        <div id="testimonial-carousel" class="testimonial-carousel box-shadow owl-carousel">
            <div class="testi-item d-flex align-items-center">
                <img src="img/testi-1.jpg" alt="img">
                <div class="testi-content">
                    <p>"Thank you for guiding us through the construction process, understanding, and always ready to
                        accommodate our needs. We love our new space and know that it was built by the very best!"</p>
                    <h3>Kyle Frederick</h3>
                    <ul class="rattings">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                    <span>Director</span>
                </div>
                <i class="fa fa-quote-right"></i>
            </div>
            <div class="testi-item d-flex align-items-center">
                <img src="img/testi-2.jpg" alt="img">
                <div class="testi-content">
                    <p>"Thank you for guiding us through the construction process, understanding, and always ready to
                        accommodate our needs. We love our new space and know that it was built by the very best!"</p>
                    <h3>Valentin Lacoste</h3>
                    <ul class="rattings">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                    <span>Director</span>
                </div>
                <i class="fa fa-quote-right"></i>
            </div>
            <div class="testi-item d-flex align-items-center">
                <img src="img/testi-3.jpg" alt="img">
                <div class="testi-content">
                    <p>"Thank you for guiding us through the construction process, understanding, and always ready to
                        accommodate our needs. We love our new space and know that it was built by the very best!"</p>
                    <h3>José Carpio</h3>
                    <ul class="rattings">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                    <span>Director</span>
                </div>
                <i class="fa fa-quote-right"></i>
            </div>
        </div>
    </div>
</section>
<div class="sponsor-section">
    <div class="container">
        <div id="sponsor-carousel" class="sponsor-carousel owl-carousel">
            <div class="sponsor-item">
                <img src="img/sponsor1.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor2.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor3.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor4.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor5.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor6.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor7.png" alt="sponsor">
            </div>
            <div class="sponsor-item">
                <img src="img/sponsor8.png" alt="sponsor">
            </div>
        </div>
    </div>
</div>
{% endblock main_content %}

templates/base.html
<!doctype html>
{% load static %}

<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->

<!-- index.html  29 Nov 2019 03:27:29 GMT -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Construction & Building HTML Template">
    <meta name="author" content="AlexaTheme">

    <title>{% block title %}{% endblock title %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% if info.favicon%} {{ info.favicon.url }} {% endif %}">

    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">

    <link rel="stylesheet" href="{% static 'css/elegant-line-icons.css' %}">

    <link rel="stylesheet" href="{% static 'css/elegant-font-icons.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/slick.css' %}">

    <link rel="stylesheet" href="{% static 'css/slider.css' %}">

    <link rel="stylesheet" href="{% static 'css/odometer.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/venobox/venobox.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade
    your browser</a> to improve your experience.</p>
<![endif]-->
<div class="site-preloader-wrap">
    <div class="spinner"></div>
</div>
{% include 'header.html' %}

{% block main_content %}

{% endblock main_content %}
{% include 'footer.html' %}

<a data-scroll href="#header" id="scroll-to-top"><i class="arrow_carrot-up"></i></a>
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>

<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

<script src="{% static 'js/vendor/tether.min.js' %}"></script>

<script src="{% static 'js/vendor/headroom.min.js' %}"></script>

<script src="{% static 'js/vendor/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/vendor/smooth-scroll.min.js' %}"></script>

<script src="{% static 'js/vendor/venobox.min.js' %}"></script>

<script src="{% static 'js/vendor/jquery.ajaxchimp.min.js' %}"></script>

<script src="{% static 'js/vendor/slick.min.js' %}"></script>

<script src="{% static 'js/vendor/waypoints.min.js' %}"></script>

<script src="{% static 'js/vendor/odometer.min.js' %}"></script>

<script src="{% static 'js/vendor/wow.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

</body>

<!-- index.html  29 Nov 2019 03:30:38 GMT -->
</html>

templates/footer.html
<section class="widget-section padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6 sm-padding">
                <div class="widget-content">
                    <a href="#">
                        {% if info.footer_logo %}
                        <img src="{{ info.footer_logo.url }}" alt="Indico">
                        {% endif %}
                        
                    <p class="text-light">{{ info.description }}</p>
                </div>
            </div>
            <div class="col-lg-2 col-sm-6 sm-padding">
                <div class="widget-content">
                    <h4>Company</h4>
                    <ul class="widget-links">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Our Services</a></li>
                        <li><a href="#">Clients Reviews</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6 sm-padding">
                <div class="widget-content">
                    <h4>Headquaters</h4>
                    <p>{{ info.address }}</p>
                    <span><a class="text-light" href="mailto:{{ info.email }}">{{ info.email }}</a></span>
                    <span>{{ info.phone }}</span>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6 sm-padding">
                <div class="widget-content">
                    <h4>Newslatter Subscription</h4>
                    <p>Subscribe and get 10% off from our <br>architecture company.</p>
                    <div class="subscribe-box clearfix">
                        <div class="subscribe-form-wrap">
                            <form action="#" class="subscribe-form">
                                <input type="email" name="email" id="subs-email" class="form-input"
                                       placeholder="Enter Your Email Address...">
                                <button type="submit" class="submit-btn">Subscribe</button>
                                <div id="subscribe-result">
                                    <p class="subscription-success"></p>
                                    <p class="subscription-error"></p>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<footer class="footer-section align-center">
    <div class="container">
        <p><a href="templateshub.net">Templates Hub</a></p>
    </div>
</footer>

templates/header.html
<header class="header">
    <div class="primary-header">
        <div class="container">
            <div class="primary-header-inner">
                <div class="header-logo">
                    <a href="#">
                        
                        {% if info.header_logo %}
                        <img src="{{ info.header_logo.url }}" alt="Indico">
                        {% endif %}
                            
                        
                    </a>
                </div>
                <div class="header-menu-wrap">
                    <ul class="dl-menu">
                        <li><a href="{% url 'home:home' %}">Home</a></li>
                        <li><a href="{% url 'about:about-us' %}">About</a></li>
                        <li><a href="{% url 'service:service' %}">Services</a></li>
                        <li><a href="{% url 'service:service' %}">Projects</a></li>
                        <li><a href="testimonial.html">Testimonial</a></li>
                        <li><a href="{% url 'service:service' %}">Blog</a></li>
                        <li><a href="team.html">Our Team</a></li>
                        <li><a href="contact.html">Contact</a></li>
                    </ul>
                </div>
                <div class="header-right">
                    <a class="menu-btn" href="#">Request a Quote</a>

                    <div class="mobile-menu-icon">
                        <div class="burger-menu">
                            <div class="line-menu line-half first-line"></div>
                            <div class="line-menu"></div>
                            <div class="line-menu line-half last-line"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/project/project_detail.html
{% extends 'base.html' %}
{% load static %}
{% block main_content %}
<section class="page-header padding">
    <div class="container">
        <div class="page-content text-center">
            <h2>{{ single_project.title}}</h2>
            <p>{{ single_project.sub_title }}</p>
        </div>
    </div>
</section>
{% for i in single_project.project_image.all %}
 <img src="{{i.image.url}}" alt="img">
{% endfor %}
<section class="project-single-section padding">
    <div class="container">
        <div class="row project-single-wrap align-items-center">
            <div class="col-md-6 sm-padding">
                <div id="project-single-carousel"
                     class="project-single-carousel box-shadow owl-carousel owl-theme owl-loaded">


                    <div class="owl-stage-outer">
                        <div class="owl-stage"
                             style="transform: translate3d(-2725px, 0px, 0px); transition: all 0.5s ease 0s; width: 3815px;">

                            <!--<div class="owl-item" style="width: 540px; margin-right: 5px;">

                                <div class="single-carousel">
                                    <img src="" alt="img">
                                </div>

                            </div>

                            <div class="owl-item cloned" style="width: 540px; margin-right: 5px;">
                                <div class="single-carousel">
                                    <img src="img/project-s-3.jpg" alt="img">
                                </div>
                            </div>
                            <div class="owl-item" style="width: 540px; margin-right: 5px;">
                                <div class="single-carousel">
                                    <img src="img/project-s-1.jpg" alt="img">
                                </div>
                            </div>
                            <div class="owl-item" style="width: 540px; margin-right: 5px;">
                                <div class="single-carousel">
                                    <img src="img/project-s-2.jpg" alt="img">
                                </div>
                            </div>
                            <div class="owl-item" style="width: 540px; margin-right: 5px;">
                                <div class="single-carousel">
                                    <img src="img/project-s-3.jpg" alt="img">
                                </div>
                            </div>
                            <div class="owl-item cloned active" style="width: 540px; margin-right: 5px;">
                                <div class="single-carousel">
                                    <img src="img/project-s-1.jpg" alt="img">
                                </div>
                            </div>-->
                            {% for i in single_project.project_image.all %}
                            <div class="owl-item" style="width: 540px; margin-right: 5px;">
                                <div class="single-carousel">
<!--                                    <img src="img/project-s-2.jpg" alt="img">-->
                                    <img src="{{ i.image.url }}" alt="img">
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="owl-controls">
                        <div class="owl-nav">
                            <div class="owl-prev" style="display: none;"><i class="fa fa-caret-left"></i></div>
                            <div class="owl-next" style="display: none;"><i class="fa fa-caret-right"></i></div>
                        </div>
                        <div class="owl-dots" style="">
                            <div class="owl-dot active"><span></span></div>
                            <div class="owl-dot"><span></span></div>
                            <div class="owl-dot"><span></span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 sm-padding">
                <div class="project-single-content">
                    <h2>{{ single_project.title }}</h2>
                    <p>{{ single_project.description }}</p>
                    <ul class="project-details">
                        <li><span>Architects</span>: {{ single_project.architects }}</li>
                        <li><span>Location</span>: {{ single_project.location }}</li>
                        <li><span>Category</span>:{{ single_project.category }}</li>
                        <li><span>Area</span>: {{ single_project.area }}</li>
                        <li><span>Project Year</span>: {{ single_project.project_start|date:"Y" }}/{{ single_project.project_end|date:"Y" }}</li>
                        <li><span>Manufactures</span>: {{ single_project.manufactures }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock main_content %}